services:
  - type: web
    name: roommatematch-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    rootDir: ./backend
    plan: starter
    branch: main
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_SYNC
        value: 'true'
      - key: DB_HOST
        fromDatabase:
          name: roommatematch-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: roommatematch-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: roommatematch-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: roommatematch-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: roommatematch-db
          property: password
      - key: BACKEND_BASE_URL
        value: https://roommatematch-api.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_DESTINATION_BANK_ACCOUNT
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: roommatematch-db
    plan: free
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
